language: node_js
node_js:
  - "8"
services:
  - docker
install:
  - docker pull mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
  - docker run -d --name sql_server -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=reallyStrongPwd123' -p 1433:1433 mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
  - npm install
  - docker exec -it sql_server /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "reallyStrongPwd123" -Q 'CREATE DATABASE jsreport; ALTER DATABASE jsreport SET READ_COMMITTED_SNAPSHOT ON;'
script: USE_DOCKER_CONNECTION=true npm run test-with-db
